package com.rad8329.simpleswingapp.negocio.gui.vistas;

import com.rad8329.simpleswingapp.negocio.entidad.Zona;
import com.rad8329.simpleswingapp.negocio.excepcion.ValidacionExcepcion;
import com.rad8329.simpleswingapp.negocio.gui.controles.ZonaControlador;
import com.rad8329.simpleswingapp.negocio.gui.modelos.ZonaTablaModelo;

import javax.swing.*;

public class ZonaPanel extends javax.swing.JPanel {

    private static final long serialVersionUID = 6968195732586101334L;
    private final ZonaTablaModelo modelo;
    private final ZonaControlador control;

    /**
     * @param modelo  Un modelo extendido de AbstractTableModel
     * @param control Una implementación de ControladorInterface
     */
    public ZonaPanel(ZonaTablaModelo modelo, ZonaControlador control) {
        this.modelo = modelo;
        this.control = control;
        super.setName(control.getTitulo());

        initComponents();
    }

    public ZonaTablaModelo getModelo() {
        return modelo;
    }

    /*
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelFormulario = new javax.swing.JPanel();
        BotonGuardar = new javax.swing.JButton();
        BotonLimpiar = new javax.swing.JButton();
        BotonBorrar = new javax.swing.JButton();
        LabelCodigo = new javax.swing.JLabel();
        TextFieldCodigo = new javax.swing.JTextField();
        LabelNombre = new javax.swing.JLabel();
        TextFieldNombre = new javax.swing.JTextField();
        LabelControlAcceso = new javax.swing.JLabel();
        CheckBoxControlAcceso = new javax.swing.JCheckBox();
        LabelDireccionIP = new javax.swing.JLabel();
        TextFieldDireccionIP = new javax.swing.JTextField();
        LabelDescripcion = new javax.swing.JLabel();
        ScrollPanelDescripcion = new javax.swing.JScrollPane();
        TextAreaDescripcion = new javax.swing.JTextArea();
        ScrollPanelTabla = new javax.swing.JScrollPane();
        Tablezonas = new javax.swing.JTable();
        LabelID = new javax.swing.JLabel();

        PanelFormulario.setBackground(new java.awt.Color(240, 236, 232));

        BotonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/save-icon.png"))); // NOI18N
        BotonGuardar.setText("Guardar");
        BotonGuardar.setFocusable(false);
        BotonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGuardarActionPerformed(evt);
            }
        });

        BotonLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/clear-icon.png"))); // NOI18N
        BotonLimpiar.setText("Limpiar");
        BotonLimpiar.setFocusable(false);
        BotonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonLimpiarActionPerformed(evt);
            }
        });

        BotonBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/delete-icon.png"))); // NOI18N
        BotonBorrar.setText("Eliminar");
        BotonBorrar.setFocusable(false);
        BotonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBorrarActionPerformed(evt);
            }
        });

        LabelCodigo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LabelCodigo.setText("Código:");

        TextFieldCodigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TextFieldCodigo.setMaximumSize(new java.awt.Dimension(2147483647, 23));
        TextFieldCodigo.setPreferredSize(new java.awt.Dimension(6, 20));

        LabelNombre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LabelNombre.setText("Nombre:");

        TextFieldNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TextFieldNombre.setMaximumSize(new java.awt.Dimension(2147483647, 23));
        TextFieldNombre.setPreferredSize(new java.awt.Dimension(6, 20));

        LabelControlAcceso.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LabelControlAcceso.setText("Control de acceso:");

        LabelDireccionIP.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LabelDireccionIP.setText("Dirección IP:");

        TextFieldDireccionIP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TextFieldDireccionIP.setMaximumSize(new java.awt.Dimension(2147483647, 23));
        TextFieldDireccionIP.setPreferredSize(new java.awt.Dimension(6, 20));

        LabelDescripcion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LabelDescripcion.setText("Descripción:");

        TextAreaDescripcion.setColumns(20);
        TextAreaDescripcion.setRows(5);
        ScrollPanelDescripcion.setViewportView(TextAreaDescripcion);

        ScrollPanelTabla.setBackground(new java.awt.Color(255, 255, 255));
        ScrollPanelTabla.setBorder(null);
        ScrollPanelTabla.setFocusable(false);

        Tablezonas.setModel(this.modelo);
        Tablezonas.setFocusable(false);
        Tablezonas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablezonasMouseClicked(evt);
            }
        });
        ScrollPanelTabla.setViewportView(Tablezonas);

        LabelID.setFocusable(false);

        javax.swing.GroupLayout PanelFormularioLayout = new javax.swing.GroupLayout(PanelFormulario);
        PanelFormulario.setLayout(PanelFormularioLayout);
        PanelFormularioLayout.setHorizontalGroup(
                PanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelFormularioLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(ScrollPanelTabla)
                                .addGap(10, 10, 10))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelFormularioLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(PanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelFormularioLayout.createSequentialGroup()
                                                .addGroup(PanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(PanelFormularioLayout.createSequentialGroup()
                                                                .addGap(41, 41, 41)
                                                                .addComponent(LabelDescripcion)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(ScrollPanelDescripcion))
                                                        .addGroup(PanelFormularioLayout.createSequentialGroup()
                                                                .addGroup(PanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(LabelCodigo)
                                                                        .addComponent(LabelControlAcceso))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(PanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(PanelFormularioLayout.createSequentialGroup()
                                                                                .addComponent(CheckBoxControlAcceso)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                                                                .addComponent(LabelDireccionIP))
                                                                        .addComponent(TextFieldCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                .addGap(30, 30, 30)
                                                                .addGroup(PanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addGroup(PanelFormularioLayout.createSequentialGroup()
                                                                                .addComponent(LabelNombre)
                                                                                .addGap(46, 46, 46)
                                                                                .addComponent(TextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addComponent(TextFieldDireccionIP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                                .addGap(36, 36, 36)
                                                .addGroup(PanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(BotonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(BotonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelFormularioLayout.createSequentialGroup()
                                                                .addComponent(LabelID)
                                                                .addGap(59, 59, 59))))
                                        .addComponent(BotonBorrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
        );
        PanelFormularioLayout.setVerticalGroup(
                PanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelFormularioLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(PanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(PanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(BotonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(TextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(LabelNombre))
                                        .addGroup(PanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(LabelCodigo)
                                                .addComponent(TextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(PanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(PanelFormularioLayout.createSequentialGroup()
                                                .addGap(14, 14, 14)
                                                .addComponent(BotonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(LabelID)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(PanelFormularioLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                                                .addGroup(PanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(CheckBoxControlAcceso, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelFormularioLayout.createSequentialGroup()
                                                                        .addComponent(LabelControlAcceso)
                                                                        .addGap(12, 12, 12)))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(TextFieldDireccionIP, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(LabelDireccionIP)))
                                                .addGap(31, 31, 31)
                                                .addGroup(PanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(LabelDescripcion)
                                                        .addComponent(ScrollPanelDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(26, 26, 26)))
                                .addComponent(ScrollPanelTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(BotonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15))
        );

        LabelID.setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, 0)
                                .addComponent(PanelFormulario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, 0)
                                .addComponent(PanelFormulario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void limpiar() {
        TextFieldCodigo.setText("");
        TextFieldNombre.setText("");
        TextAreaDescripcion.setText("");
        TextFieldDireccionIP.setText("");
        CheckBoxControlAcceso.setSelected(false);
    }

    private void BotonGuardarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BotonGuardarActionPerformed

        boolean errores = false;

        String mensaje = "La zona fue agregada con éxito";

        try {
            int codigo;

            try {
                codigo = Integer.parseInt(TextFieldCodigo.getText());
            } catch (NumberFormatException ex) {

                throw new ValidacionExcepcion("Código debe ser númerico y no vacío");
            }

            Zona zona = new Zona(codigo, TextFieldNombre.getText(), TextAreaDescripcion.getText(),
                    CheckBoxControlAcceso.isSelected(), TextFieldDireccionIP.getText());

            if (!LabelID.getText().isEmpty()) {
                control.actualizarRegistro(Integer.parseInt(LabelID.getText()), zona);
                mensaje = "La zona fue actualizado con éxito";
            } else {
                control.agregarRegistro(zona, true);
            }

        } catch (ValidacionExcepcion ex) {
            errores = true;
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }

        if (!errores) {
            limpiar();

            JOptionPane.showMessageDialog(this, mensaje);
        }
    }// GEN-LAST:event_BotonGuardarActionPerformed

    private void BotonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BotonLimpiarActionPerformed
        limpiar();
    }// GEN-LAST:event_BotonLimpiarActionPerformed

    private void TablezonasMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_TablezonasMouseClicked
        JTable source = (JTable) evt.getSource();
        int fila = source.rowAtPoint(evt.getPoint());

        Zona zona = control.conseguirRegistro(fila);

        TextFieldCodigo.setText(Integer.toString(zona.getCodigo_zona()));
        TextFieldNombre.setText(zona.getNombre());
        TextAreaDescripcion.setText(zona.getDescripcion());
        TextFieldDireccionIP.setText(zona.getDireccion_ip_cerradura());
        CheckBoxControlAcceso.setSelected(zona.tieneControl_de_acceso());

        LabelID.setText(Integer.toString(fila));// Para saber si debemos actualizarRegistro
    }// GEN-LAST:event_TablezonasMouseClicked

    private void BotonBorrarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BotonBorrarActionPerformed

        if (!LabelID.getText().isEmpty()) {
            int fila = Integer.parseInt(LabelID.getText());

            control.removerRegistro(fila);

            limpiar();

            JOptionPane.showMessageDialog(this, "La zona fue eliminada con éxito");
        }
    }// GEN-LAST:event_BotonBorrarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonBorrar;
    private javax.swing.JButton BotonGuardar;
    private javax.swing.JButton BotonLimpiar;
    private javax.swing.JCheckBox CheckBoxControlAcceso;
    private javax.swing.JLabel LabelCodigo;
    private javax.swing.JLabel LabelControlAcceso;
    private javax.swing.JLabel LabelDescripcion;
    private javax.swing.JLabel LabelDireccionIP;
    private javax.swing.JLabel LabelID;
    private javax.swing.JLabel LabelNombre;
    private javax.swing.JPanel PanelFormulario;
    private javax.swing.JScrollPane ScrollPanelDescripcion;
    private javax.swing.JScrollPane ScrollPanelTabla;
    private javax.swing.JTable Tablezonas;
    private javax.swing.JTextArea TextAreaDescripcion;
    private javax.swing.JTextField TextFieldCodigo;
    private javax.swing.JTextField TextFieldDireccionIP;
    private javax.swing.JTextField TextFieldNombre;
    // End of variables declaration//GEN-END:variables
}
