package com.rad8329.simpleswingapp.gui.zona;

import com.rad8329.simpleswingapp.gui.comun.vista.Utilidades;
import com.rad8329.simpleswingapp.dominio.zona.Zona;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import com.rad8329.simpleswingapp.dominio.comun.excepcion.ExcepcionValidacion;
import com.rad8329.simpleswingapp.dominio.comun.vista.VistaModeloInterface;
import com.rad8329.simpleswingapp.gui.comun.vista.Panel;

public class ZonaPanel extends Panel implements VistaModeloInterface<ZonaTablaModelo> {

    private static final long serialVersionUID = -6005578702230589049L;
    private final ZonaTablaModelo modelo;
    protected final ZonaControlador control;

    /**
     *
     * @param modelo
     * @param control
     */
    public ZonaPanel(ZonaTablaModelo modelo, ZonaControlador control) {
        this.modelo = modelo;
        this.control = control;
        super.setName(control.getTitulo());

        initComponents();
    }

    @Override
    public ZonaTablaModelo getModelo() {
        return modelo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelFormulario.setBackground(new java.awt.Color(240, 236, 232));
        PanelFormulario.setMinimumSize(new java.awt.Dimension(900, 565));
        PanelFormulario.setPreferredSize(new java.awt.Dimension(900, 565));
        PanelFormulario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/save-icon.png"))); // NOI18N
        BotonGuardar.setText("Guardar");
        BotonGuardar.setFocusable(false);
        BotonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGuardarActionPerformed(evt);
            }
        });
        PanelFormulario.add(BotonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 30, 155, 36));

        BotonLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/clear-icon.png"))); // NOI18N
        BotonLimpiar.setText("Limpiar");
        BotonLimpiar.setFocusable(false);
        BotonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonLimpiarActionPerformed(evt);
            }
        });
        PanelFormulario.add(BotonLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 80, 155, 36));

        BotonBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/drop-icon.png"))); // NOI18N
        BotonBorrar.setText("Eliminar");
        BotonBorrar.setFocusable(false);
        BotonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBorrarActionPerformed(evt);
            }
        });
        PanelFormulario.add(BotonBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 510, 155, 36));

        LabelCodigo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LabelCodigo.setText("Código:");
        PanelFormulario.add(LabelCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 43, -1, -1));

        TextFieldCodigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TextFieldCodigo.setMaximumSize(new java.awt.Dimension(2147483647, 23));
        TextFieldCodigo.setPreferredSize(new java.awt.Dimension(6, 20));
        PanelFormulario.add(TextFieldCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 32, 176, 36));

        LabelNombre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LabelNombre.setText("Nombre:");
        PanelFormulario.add(LabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 43, -1, -1));

        TextFieldNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TextFieldNombre.setMaximumSize(new java.awt.Dimension(2147483647, 23));
        TextFieldNombre.setPreferredSize(new java.awt.Dimension(6, 20));
        PanelFormulario.add(TextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 33, 280, 36));

        LabelControlAcceso.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LabelControlAcceso.setText("Control de acceso:");
        PanelFormulario.add(LabelControlAcceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, -1, -1));
        PanelFormulario.add(CheckBoxControlAcceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, -1, 35));

        LabelDireccionIP.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LabelDireccionIP.setText("Dirección IP:");
        PanelFormulario.add(LabelDireccionIP, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        TextFieldDireccionIP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TextFieldDireccionIP.setMaximumSize(new java.awt.Dimension(2147483647, 23));
        TextFieldDireccionIP.setPreferredSize(new java.awt.Dimension(6, 20));
        PanelFormulario.add(TextFieldDireccionIP, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 176, 36));

        LabelDescripcion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LabelDescripcion.setText("Descripción:");
        PanelFormulario.add(LabelDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, -1, -1));

        TextAreaDescripcion.setColumns(20);
        TextAreaDescripcion.setRows(5);
        ScrollPanelDescripcion.setViewportView(TextAreaDescripcion);

        PanelFormulario.add(ScrollPanelDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 290, 70));

        ScrollPanelTabla.setBackground(new java.awt.Color(255, 255, 255));
        ScrollPanelTabla.setBorder(null);
        ScrollPanelTabla.setFocusable(false);

        TablaDatos.setModel(this.modelo);
        TablaDatos.setFocusable(false);
        TablaDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaDatosMouseClicked(evt);
            }
        });
        TablaDatos.getColumnModel().getColumn(0).setMaxWidth(50);
        ScrollPanelTabla.setViewportView(TablaDatos);

        PanelFormulario.add(ScrollPanelTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 216, 850, 270));

        LabelID.setFocusable(false);
        PanelFormulario.add(LabelID, new org.netbeans.lib.awtextra.AbsoluteConstraints(824, 229, -1, -1));
        LabelID.setVisible(false);

        add(PanelFormulario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void limpiar() {
        TextFieldCodigo.setText("");
        TextFieldNombre.setText("");
        TextAreaDescripcion.setText("");
        TextFieldDireccionIP.setText("");
        CheckBoxControlAcceso.setSelected(false);
        LabelID.setText("");
    }

    private void BotonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGuardarActionPerformed

        String mensaje;

        try {
            Zona zona = new Zona(
                    Utilidades.capturarEntero(TextFieldCodigo, "Código").get(),
                    TextFieldNombre.getText(),
                    TextAreaDescripcion.getText(),
                    CheckBoxControlAcceso.isSelected(),
                    TextFieldDireccionIP.getText()
            );

            if (!LabelID.getText().isEmpty()) {
                if (control.actualizarRegistro(Integer.parseInt(LabelID.getText()), zona)) {
                    mensaje = "La zona fue actualizado con éxito";
                    limpiar();
                } else {
                    mensaje = "Ocurrió un problema al intentar actualizar la zona";

                }
            } else {
                if (control.agregarRegistro(zona)) {
                    mensaje = "La zona fue agregada con éxito";
                    limpiar();
                } else {
                    mensaje = "Ocurrió un problema al intentar agregar la zona";
                }
            }

            JOptionPane.showMessageDialog(this, mensaje);

        } catch (ExcepcionValidacion ve) {
            JOptionPane.showMessageDialog(this, ve.getMessage());
        }
    }//GEN-LAST:event_BotonGuardarActionPerformed

    private void BotonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_BotonLimpiarActionPerformed

    private void TablaDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaDatosMouseClicked
        JTable source = (JTable) evt.getSource();
        int fila = source.rowAtPoint(evt.getPoint());
        
        Zona zona = control.conseguirRegistro(fila);

        TextFieldCodigo.setText(Integer.toString(zona.getCodigo_zona()));
        TextFieldNombre.setText(zona.getNombre());
        TextAreaDescripcion.setText(zona.getDescripcion());
        TextFieldDireccionIP.setText(zona.getDireccion_ip_cerradura());
        CheckBoxControlAcceso.setSelected(zona.tieneControl_de_acceso());

        LabelID.setText(Integer.toString(fila));// Para saber si debemos actualizar el registro
    }//GEN-LAST:event_TablaDatosMouseClicked

    private void BotonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBorrarActionPerformed

        if (!LabelID.getText().isEmpty()) {
            int fila = Integer.parseInt(LabelID.getText());

            String mensaje;

            if (control.removerRegistro(fila)) {
                limpiar();

                mensaje = "La zona fue eliminada con éxito";
            } else {
                mensaje = "Ocurrió un problema al intentar eliminar la zona";
            }

            JOptionPane.showMessageDialog(this, mensaje);
        }
    }//GEN-LAST:event_BotonBorrarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private final javax.swing.JButton BotonBorrar = new javax.swing.JButton();
    private final javax.swing.JButton BotonGuardar = new javax.swing.JButton();
    private final javax.swing.JButton BotonLimpiar = new javax.swing.JButton();
    private final javax.swing.JCheckBox CheckBoxControlAcceso = new javax.swing.JCheckBox();
    private final javax.swing.JLabel LabelCodigo = new javax.swing.JLabel();
    private final javax.swing.JLabel LabelControlAcceso = new javax.swing.JLabel();
    private final javax.swing.JLabel LabelDescripcion = new javax.swing.JLabel();
    private final javax.swing.JLabel LabelDireccionIP = new javax.swing.JLabel();
    private final javax.swing.JLabel LabelID = new javax.swing.JLabel();
    private final javax.swing.JLabel LabelNombre = new javax.swing.JLabel();
    private final javax.swing.JPanel PanelFormulario = new javax.swing.JPanel();
    private final javax.swing.JScrollPane ScrollPanelDescripcion = new javax.swing.JScrollPane();
    private final javax.swing.JScrollPane ScrollPanelTabla = new javax.swing.JScrollPane();
    private final javax.swing.JTable TablaDatos = new javax.swing.JTable();
    private final javax.swing.JTextArea TextAreaDescripcion = new javax.swing.JTextArea();
    private final javax.swing.JTextField TextFieldCodigo = new javax.swing.JTextField();
    private final javax.swing.JTextField TextFieldDireccionIP = new javax.swing.JTextField();
    private final javax.swing.JTextField TextFieldNombre = new javax.swing.JTextField();
    // End of variables declaration//GEN-END:variables
}
