package com.rad8329.simpleswingapp.gui.zona;

import com.rad8329.simpleswingapp.gui.comun.vista.OpcionCombo;
import java.util.ArrayList;
import java.util.List;
import com.rad8329.simpleswingapp.dominio.comun.entidad.EntidadOpcionableInterface;
import com.rad8329.simpleswingapp.dominio.comun.excepcion.ExcepcionValidacion;
import com.rad8329.simpleswingapp.dominio.comun.vista.VistaModeloInterface;
import com.rad8329.simpleswingapp.dominio.zona.ZonaReporteValidador;
import com.rad8329.simpleswingapp.gui.comun.vista.Panel;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

public class ZonaReportePanel extends Panel implements VistaModeloInterface<ZonaReporteTablaModelo> {

    private static final long serialVersionUID = 3165359248785892336L;
    private final ZonaReporteTablaModelo modelo;
    private final List<OpcionCombo> zonas = new ArrayList<>();
    protected final ZonaReporteControlador control;

    /**
     * @param modelo
     * @param control
     */
    public ZonaReportePanel(ZonaReporteTablaModelo modelo, ZonaReporteControlador control) {
        this.modelo = modelo;
        this.control = control;
        initComponents();
        cargarComboZonas();
        AutoCompleteDecorator.decorate(ComboBoxZona);
    }

    private void cargarComboZonas() {
        OpcionCombo opcion1 = EntidadOpcionableInterface.crear("-1", "");
        zonas.add(opcion1);
        ComboBoxZona.addItem(opcion1);

        control.listaDeZonas().forEach(
                zona -> {
                    OpcionCombo opcion = zona.opcionCombo();
                    zonas.add(opcion);
                    ComboBoxZona.addItem(opcion);
                }
        );

        ComboBoxZona.setSelectedIndex(-1);
    }

    @Override
    public ZonaReporteTablaModelo getModelo() {
        return modelo;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextFieldFechaInicio = new javax.swing.JTextField();
        TextFieldFechaFin = new javax.swing.JTextField();

        setLayout(new java.awt.CardLayout());

        PanelFormulario.setBackground(new java.awt.Color(240, 236, 232));
        PanelFormulario.setMinimumSize(new java.awt.Dimension(840, 470));
        PanelFormulario.setPreferredSize(new java.awt.Dimension(840, 470));
        PanelFormulario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/search-icon.png"))); // NOI18N
        BotonBuscar.setFocusable(false);
        BotonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscarActionPerformed(evt);
            }
        });
        PanelFormulario.add(BotonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, 50, 40));

        BotonLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/clear-icon.png"))); // NOI18N
        BotonLimpiar.setFocusable(false);
        BotonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonLimpiarActionPerformed(evt);
            }
        });
        PanelFormulario.add(BotonLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 20, 50, 40));

        LabelZona.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LabelZona.setText("Zona:");
        PanelFormulario.add(LabelZona, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        ComboBoxZona.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PanelFormulario.add(ComboBoxZona, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 260, 40));

        ScrollPanelTabla.setBackground(new java.awt.Color(255, 255, 255));
        ScrollPanelTabla.setBorder(null);
        ScrollPanelTabla.setFocusable(false);
        ScrollPanelTabla.setPreferredSize(new java.awt.Dimension(820, 380));

        TablaDatos.setModel(this.modelo);
        TablaDatos.setFocusable(false);
        TablaDatos.getColumnModel().getColumn(0).setMaxWidth(50);
        ScrollPanelTabla.setViewportView(TablaDatos);

        PanelFormulario.add(ScrollPanelTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 81, -1, -1));
        PanelFormulario.add(TextFieldFechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 130, 40));

        LabelFechaFin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LabelFechaFin.setText("fin:");
        PanelFormulario.add(LabelFechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, -1, -1));

        LabelFechaInicio.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LabelFechaInicio.setText("Fecha inicio:");
        PanelFormulario.add(LabelFechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, -1, -1));
        PanelFormulario.add(TextFieldFechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, 130, 40));

        add(PanelFormulario, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void limpiar() {
        ComboBoxZona.setSelectedIndex(-1);
        TextFieldFechaInicio.setText("");
        TextFieldFechaFin.setText("");
        control.limpiar();
    }

    private void BotonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_BotonLimpiarActionPerformed

    private void BotonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscarActionPerformed

        try {
            control.buscar(
                    new ZonaReporteValidador(
                            Integer.parseInt(((OpcionCombo) ComboBoxZona.getSelectedItem()).getLlave()),
                            TextFieldFechaInicio.getText(),
                            TextFieldFechaFin.getText()
                    )
            );
        } catch (ExcepcionValidacion ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        } catch (NullPointerException ne) {
            JOptionPane.showMessageDialog(this, "La zona es necesaria");
        }
    }//GEN-LAST:event_BotonBuscarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private final javax.swing.JButton BotonBuscar = new javax.swing.JButton();
    private final javax.swing.JButton BotonLimpiar = new javax.swing.JButton();
    private final javax.swing.JComboBox ComboBoxZona = new javax.swing.JComboBox();
    private final javax.swing.JLabel LabelFechaFin = new javax.swing.JLabel();
    private final javax.swing.JLabel LabelFechaInicio = new javax.swing.JLabel();
    private final javax.swing.JLabel LabelZona = new javax.swing.JLabel();
    private final javax.swing.JPanel PanelFormulario = new javax.swing.JPanel();
    private final javax.swing.JScrollPane ScrollPanelTabla = new javax.swing.JScrollPane();
    private final javax.swing.JTable TablaDatos = new javax.swing.JTable();
    private javax.swing.JTextField TextFieldFechaFin;
    private javax.swing.JTextField TextFieldFechaInicio;
    // End of variables declaration//GEN-END:variables
}
