package com.rad8329.simpleswingapp.gui.evento;

import com.rad8329.simpleswingapp.gui.comun.vista.OpcionCombo;
import java.util.ArrayList;
import java.util.List;
import com.rad8329.simpleswingapp.dominio.comun.entidad.EntidadOpcionableInterface;
import com.rad8329.simpleswingapp.dominio.comun.excepcion.ExcepcionValidacion;
import com.rad8329.simpleswingapp.dominio.comun.vista.VistaModeloInterface;
import com.rad8329.simpleswingapp.dominio.evento.EventoReporteValidador;
import com.rad8329.simpleswingapp.gui.comun.vista.Panel;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

public class EventoReportePanel extends Panel implements VistaModeloInterface<EventoReporteTablaModelo> {

    private static final long serialVersionUID = 5328341883143985326L;
    private final EventoReporteTablaModelo modelo;
    private final List<OpcionCombo> eventos = new ArrayList<>();
    protected final EventoReporteControlador control;

    /**
     * @param modelo
     * @param control
     */
    public EventoReportePanel(EventoReporteTablaModelo modelo, EventoReporteControlador control) {
        this.modelo = modelo;
        this.control = control;

        initComponents();
        cargarComboEventos();
        AutoCompleteDecorator.decorate(ComboBoxEvento);
    }

    private void cargarComboEventos() {
        OpcionCombo opcion1 = EntidadOpcionableInterface.crear("-1", "");
        eventos.add(opcion1);
        ComboBoxEvento.addItem(opcion1);

        control.listaDeEventos().forEach(
                evento -> {
                    OpcionCombo opcion = evento.opcionCombo();
                    eventos.add(opcion);
                    ComboBoxEvento.addItem(opcion);
                }
        );

        ComboBoxEvento.setSelectedIndex(-1);
    }

    @Override
    public EventoReporteTablaModelo getModelo() {
        return modelo;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.CardLayout());

        PanelFormulario.setBackground(new java.awt.Color(240, 236, 232));
        PanelFormulario.setMinimumSize(new java.awt.Dimension(840, 470));
        PanelFormulario.setPreferredSize(new java.awt.Dimension(840, 470));
        PanelFormulario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/search-icon.png"))); // NOI18N
        BotonBuscar.setFocusable(false);
        BotonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscarActionPerformed(evt);
            }
        });
        PanelFormulario.add(BotonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, 50, 40));

        BotonLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/clear-icon.png"))); // NOI18N
        BotonLimpiar.setFocusable(false);
        BotonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonLimpiarActionPerformed(evt);
            }
        });
        PanelFormulario.add(BotonLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 20, 50, 40));

        LabelEvento.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LabelEvento.setText("Evento:");
        PanelFormulario.add(LabelEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        ComboBoxEvento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PanelFormulario.add(ComboBoxEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 610, 40));

        ScrollPanelTabla.setBackground(new java.awt.Color(255, 255, 255));
        ScrollPanelTabla.setBorder(null);
        ScrollPanelTabla.setFocusable(false);
        ScrollPanelTabla.setPreferredSize(new java.awt.Dimension(820, 380));

        TablaDatos.setModel(this.modelo);
        TablaDatos.setFocusable(false);
        TablaDatos.getColumnModel().getColumn(0).setMaxWidth(50);
        ScrollPanelTabla.setViewportView(TablaDatos);

        PanelFormulario.add(ScrollPanelTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 81, -1, -1));

        add(PanelFormulario, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void limpiar() {
        ComboBoxEvento.setSelectedIndex(-1);
        control.limpiar();
    }

    private void BotonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_BotonLimpiarActionPerformed

    private void BotonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscarActionPerformed
        
        try {
            control.buscar(
                    new EventoReporteValidador(
                            Integer.parseInt(((OpcionCombo) ComboBoxEvento.getSelectedItem()).getLlave()))
            );

        } catch (ExcepcionValidacion ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        } catch (NullPointerException ne) {
            JOptionPane.showMessageDialog(this, "El evento es necesario");
        }
    }//GEN-LAST:event_BotonBuscarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private final javax.swing.JButton BotonBuscar = new javax.swing.JButton();
    private final javax.swing.JButton BotonLimpiar = new javax.swing.JButton();
    private final javax.swing.JComboBox ComboBoxEvento = new javax.swing.JComboBox();
    private final javax.swing.JLabel LabelEvento = new javax.swing.JLabel();
    private final javax.swing.JPanel PanelFormulario = new javax.swing.JPanel();
    private final javax.swing.JScrollPane ScrollPanelTabla = new javax.swing.JScrollPane();
    private final javax.swing.JTable TablaDatos = new javax.swing.JTable();
    // End of variables declaration//GEN-END:variables
}
